FROM mcr.microsoft.com/dotnet/sdk:5.0 AS builder
WORKDIR /source

COPY . .

# Change the Directory
WORKDIR /source/

# aspnet-core
RUN dotnet restore src/Services/ECommerce.Cart/ECommerce.Cart.csproj
RUN dotnet publish src/Services/ECommerce.Cart/ECommerce.Cart.csproj --output /ecommercecart/ --configuration Release

## Runtime
FROM mcr.microsoft.com/dotnet/aspnet:5.0

# Change the Directory
WORKDIR /ecommercecart

COPY --from=builder /ecommercecart .
ENTRYPOINT ["dotnet", "ECommerce.Cart.dll"]